#!/usr/bin/env node
/**
 * Development QA report.
 *
 * Runs the deterministic per-exhibit checklist and writes the automated,
 * human-readable report to validation/reports/QA_REPORT.md.
 *
 * The human walkthrough contract is maintained separately in
 * validation/reports/HUMAN_QA_CHECKLIST.md. This script deliberately does not
 * regenerate or overwrite that human-authored contract.
 */
import { existsSync, writeFileSync, readFileSync } from 'node:fs';
import { readJson, report, walk } from './_lib.mjs';

const mappingPath = existsSync('data/exhibit-mapping.current.json')
  ? 'data/exhibit-mapping.current.json'
  : 'data/exhibit-mapping.json';
const map = readJson(mappingPath);
const baseCopy = readJson('data/exhibit-content.json');
const revisionCopy = existsSync('data/exhibit-content.revision2.json')
  ? readJson('data/exhibit-content.revision2.json')
  : {};
const copy = { ...baseCopy, ...revisionCopy };
const index = readFileSync('src/exhibits/index.ts', 'utf8');

const projectRecords = [];
for (const f of walk('data/projects', ['.json'])) projectRecords.push(...readJson(f));
const authoredProjectIds = new Set(projectRecords.map((p) => p.id));

// Reading these files is deliberate: QA is not allowed to generate a
// reassuring report after one of its whole-museum guard suites disappears.
readFileSync('tests/accessibility.test.ts', 'utf8');
readFileSync('tests/lifecycle-memory.test.ts', 'utf8');
readFileSync('tests/persistent-environment.test.ts', 'utf8');
readFileSync('tests/environment.test.ts', 'utf8');
readFileSync('tests/traversal.test.ts', 'utf8');
readFileSync('validation/reports/HUMAN_QA_CHECKLIST.md', 'utf8');

const bespoke = new Set([...index.matchAll(/registerBespoke\(\s*'([^']+)'/g)].map((m) => m[1]));
const mappedIds = new Set(map.exhibits.map((e) => e.id));
const mappedProjectIds = new Set();

const WINGS = {
  north: 'Starsilk & Drakken', east: 'Dex Systems', south: 'Games & Play',
  west: 'Archive & Canon', media: 'Music, Promptcraft & Media', infra: 'Local Systems',
};

const CHECKS = [
  ['reachable', 'tests/traversal.test.ts — walked on the canonical route'],
  ['identifiable', 'signage over every bay opening (Detailing)'],
  ['hero object', 'tests/exhibit-quality.test.ts — real volume in three axes, >12 meshes'],
  ['fits its bay', 'tests/exhibit-quality.test.ts'],
  ['interaction works', 'tests/exhibit-quality.test.ts — controls change observable state'],
  ['reset works', 'tests/exhibit-quality.test.ts — idempotent, returns to just-activated state'],
  ['accessible content', 'tests/exhibit-quality.test.ts — heading, plaque, ≥4 body paragraphs, live state'],
  ['reduced motion', 'tests/exhibit-quality.test.ts — usable and describable with motion off'],
  ['unload / reload', 'tests/exhibit-quality.test.ts — three clean cycles, scope drains to zero'],
  ['owns only its group', 'tests/exhibit-quality.test.ts'],
];

const errors = [];
const lines = [];

lines.push('# Museum of Me — Development QA Report');
lines.push('');
lines.push(`Generated by \`npm run qa\` from \`${mappingPath}\` plus current content overlays.`);
lines.push('Per-exhibit checks below are enforced by automated tests.');
lines.push('Human visual/device evidence is listed separately and is never promoted automatically.');
lines.push('Passing this report is development evidence, not a declaration that the museum is 1.0 or release-ready.');
lines.push('');
lines.push('## Checklist applied to every exhibit');
lines.push('');
lines.push('| Check | Enforced by |');
lines.push('|---|---|');
for (const [name, by] of CHECKS) lines.push(`| ${name} | ${by} |`);
lines.push('');

const byWing = new Map();
for (const e of map.exhibits) {
  const list = byWing.get(e.wing) ?? [];
  list.push(e);
  byWing.set(e.wing, list);
}

lines.push('## Exhibits');
lines.push('');
for (const [wing, name] of Object.entries(WINGS)) {
  const list = byWing.get(wing) ?? [];
  lines.push(`### ${name} — ${list.length} exhibits`);
  lines.push('');
  lines.push('| ID | Exhibit | Tier | Projects | Implementation |');
  lines.push('|---|---|---|---|---|');
  for (const e of list) {
    for (const projectId of e.projects) {
      if (mappedProjectIds.has(projectId)) errors.push(`${projectId} is mapped more than once in ${mappingPath}`);
      mappedProjectIds.add(projectId);
      if (!authoredProjectIds.has(projectId)) errors.push(`${projectId} is mapped by ${e.id} but has no authored current project record`);
    }
    const impl = bespoke.has(e.id) ? 'bespoke' : '**SCAFFOLDING**';
    if (!bespoke.has(e.id)) errors.push(`${e.id} is still scaffolded`);
    if (!copy[e.id]) errors.push(`${e.id} has no interpretive copy`);
    lines.push(`| ${e.id} | ${e.title} — ${copy[e.id]?.subtitle ?? '—'} | ${e.tier} | ${e.projects.join(', ')} | ${impl} |`);
  }
  lines.push('');
}

for (const projectId of authoredProjectIds) {
  if (!mappedProjectIds.has(projectId)) errors.push(`${projectId} has an authored current project record but is not represented in ${mappingPath}`);
}
for (const id of bespoke) {
  if (!mappedIds.has(id)) errors.push(`bespoke implementation ${id} is not in the current mapping`);
}

lines.push('## Whole-museum automated coverage');
lines.push('');
lines.push('- Keyboard, touch, reduced motion, high-contrast/UI-scale preference contract and blur recovery: `tests/accessibility.test.ts`.');
lines.push('- Continuous exterior-to-interior canonical route through every wing and Sanctuary: `tests/traversal.test.ts`.');
lines.push('- Repeated whole-route streaming/lifecycle settling and shell budgets: `tests/lifecycle-memory.test.ts`.');
lines.push('- Always-resident refinement mesh/triangle/material/light/resource budgets: `tests/persistent-environment.test.ts`.');
lines.push('- Exterior/garden, facade, Rotunda baseline, wing identity, furnishings, atmosphere, wayfinding and exhibit colour fields: `tests/environment.test.ts`.');
lines.push('- Mapping, visitor content, privacy, frame-loop, hot-path, assets, bespoke exhibit validation, production build and bundle budgets: canonical `npm run gate`.');
lines.push('');

lines.push('## Coverage');
lines.push('');
lines.push(`- **${map.exhibits.length} / 35** physical exhibit slots`);
lines.push(`- **${mappedProjectIds.size} / ${projectRecords.length}** current project identities represented, each exactly once`);
lines.push(`- **${bespoke.size} / ${map.exhibits.length}** implemented bespoke`);
lines.push('- **1** Dexter Sanctuary, deliberately outside the exhibit count');
lines.push('');
lines.push('## Spaces outside the exhibit count');
lines.push('');
lines.push('| Space | Checks |');
lines.push('|---|---|');
lines.push('| Reliquary Rotunda | reachable, monumental, two-level continuity, orientation and neutral-hub wayfinding |');
lines.push('| Arrival plaza and entrance | reachable, intentional night exterior, garden route, signed public-building facade |');
lines.push('| Rotunda balcony | reachable by stair, connects both mezzanines |');
lines.push('| Dexter Sanctuary | `tests/sanctuary.test.ts` — below and behind the axis, hanging ears preserved, holds still under reduced motion, contains no score, badge, collectible, paw-print, achievement, unlock or reward |');
lines.push('');
lines.push('## Human-only product evidence still required');
lines.push('');
lines.push('- Recorded visual walkthrough from the night exterior through representative galleries and changed exhibit bays.');
lines.push('- Pointer-lock capture, look, Escape/loss recovery and recapture on a real browser/device.');
lines.push('- Muted-by-default audio check plus deliberate Sound-control playback/subtitle check.');
lines.push('- Representative-device frame-rate measurement and subjective composition/readability/interaction review.');
lines.push('');
lines.push('See `validation/reports/HUMAN_QA_CHECKLIST.md` for the exact manual route.');

if (map.exhibits.length !== 35) errors.push(`exhibit count is ${map.exhibits.length}, expected 35`);
if (mappedProjectIds.size !== projectRecords.length) {
  errors.push(`current project coverage is ${mappedProjectIds.size}, expected ${projectRecords.length} authored project records`);
}
if (bespoke.size !== map.exhibits.length) errors.push(`bespoke count is ${bespoke.size}, expected ${map.exhibits.length}`);

writeFileSync('validation/reports/QA_REPORT.md', lines.join('\n'));

process.exit(
  report('qa', errors, [
    `${map.exhibits.length} exhibits, ${mappedProjectIds.size} project identities, ${bespoke.size} bespoke`,
    `mapping source: ${mappingPath}`,
    'wrote validation/reports/QA_REPORT.md',
    'preserved validation/reports/HUMAN_QA_CHECKLIST.md',
  ]),
);
