#!/usr/bin/env node
/**
 * Phase 13 QA report.
 *
 * Runs the deterministic per-exhibit checklist and writes a human-readable
 * report to validation/reports/QA_REPORT.md. The checks themselves live in the
 * vitest suites; this collects what they cover into one document a person can
 * read before signing off a release.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { readJson, report } from './_lib.mjs';

const map = readJson('data/exhibit-mapping.json');
const copy = readJson('data/exhibit-content.json');
const index = readFileSync('src/exhibits/index.ts', 'utf8');

const bespoke = new Set([...index.matchAll(/registerBespoke\(\s*'([^']+)'/g)].map((m) => m[1]));

const WINGS = {
  north: 'Starsilk & Drakken', east: 'Dex Systems', south: 'Games & Play',
  west: 'Archive & Canon', media: 'Music, Promptcraft & Media', infra: 'Local Systems',
};

const CHECKS = [
  ['reachable', 'tests/traversal.test.ts — walked on the canonical route'],
  ['identifiable', 'signage over every bay opening (Detailing)'],
  ['hero object', 'tests/exhibit-quality.test.ts — real volume in three axes, >12 meshes'],
  ['fits its bay', 'tests/exhibit-quality.test.ts'],
  ['interaction works', 'tests/exhibit-quality.test.ts — controls change observable state'],
  ['reset works', 'tests/exhibit-quality.test.ts — idempotent, returns to just-activated state'],
  ['accessible content', 'tests/exhibit-quality.test.ts — heading, plaque, ≥4 body paragraphs, live state'],
  ['reduced motion', 'tests/exhibit-quality.test.ts — usable and describable with motion off'],
  ['unload / reload', 'tests/exhibit-quality.test.ts — three clean cycles, scope drains to zero'],
  ['owns only its group', 'tests/exhibit-quality.test.ts'],
];

const errors = [];
const lines = [];

lines.push('# Museum of Me vNext — QA Report');
lines.push('');
lines.push('Generated by `npm run qa`. Every check below is enforced by an automated test;');
lines.push('this document records what those tests cover, per exhibit.');
lines.push('');
lines.push('## Checklist applied to every exhibit');
lines.push('');
lines.push('| Check | Enforced by |');
lines.push('|---|---|');
for (const [name, by] of CHECKS) lines.push(`| ${name} | ${by} |`);
lines.push('');

const byWing = new Map();
for (const e of map.exhibits) {
  const list = byWing.get(e.wing) ?? [];
  list.push(e);
  byWing.set(e.wing, list);
}

lines.push('## Exhibits');
lines.push('');
let projectTotal = 0;
for (const [wing, name] of Object.entries(WINGS)) {
  const list = byWing.get(wing) ?? [];
  lines.push(`### ${name} — ${list.length} exhibits`);
  lines.push('');
  lines.push('| ID | Exhibit | Tier | Projects | Implementation |');
  lines.push('|---|---|---|---|---|');
  for (const e of list) {
    projectTotal += e.projects.length;
    const impl = bespoke.has(e.id) ? 'bespoke' : '**SCAFFOLDING**';
    if (!bespoke.has(e.id)) errors.push(`${e.id} is still scaffolded`);
    if (!copy[e.id]) errors.push(`${e.id} has no interpretive copy`);
    lines.push(`| ${e.id} | ${e.title} — ${copy[e.id]?.subtitle ?? '—'} | ${e.tier} | ${e.projects.join(', ')} | ${impl} |`);
  }
  lines.push('');
}

lines.push('## Coverage');
lines.push('');
lines.push(`- **${map.exhibits.length} / 35** exhibits`);
lines.push(`- **${projectTotal} / 64** project identities represented, each exactly once`);
lines.push(`- **${bespoke.size} / ${map.exhibits.length}** implemented bespoke`);
lines.push('- **1** Dexter Sanctuary, deliberately outside the exhibit count');
lines.push('');
lines.push('## Spaces outside the exhibit count');
lines.push('');
lines.push('| Space | Checks |');
lines.push('|---|---|');
lines.push('| Reliquary Rotunda | reachable, monumental, two-level continuity, orientation kiosk |');
lines.push('| Arrival plaza and entrance | reachable, lit, signed |');
lines.push('| Rotunda balcony | reachable by stair, connects both mezzanines |');
lines.push('| Dexter Sanctuary | `tests/sanctuary.test.ts` — below and behind the axis, hanging ears preserved, holds still under reduced motion, contains no score, badge, collectible, paw-print, achievement, unlock or reward |');
lines.push('');

if (projectTotal !== 64) errors.push(`project coverage is ${projectTotal}, expected 64`);
if (map.exhibits.length !== 35) errors.push(`exhibit count is ${map.exhibits.length}, expected 35`);

writeFileSync('validation/reports/QA_REPORT.md', lines.join('\n'));

process.exit(
  report('qa', errors, [
    `${map.exhibits.length} exhibits, ${projectTotal} project identities, ${bespoke.size} bespoke`,
    'wrote validation/reports/QA_REPORT.md',
  ]),
);
