#!/usr/bin/env node
/**
 * Phase 13 QA report.
 *
 * Runs the deterministic per-exhibit checklist and writes a human-readable
 * report to validation/reports/QA_REPORT.md. It also writes the remaining human
 * walkthrough contract separately so automated evidence can never be mistaken
 * for visual/device sign-off.
 */
import { writeFileSync, readFileSync } from 'node:fs';
import { readJson, report } from './_lib.mjs';

const map = readJson('data/exhibit-mapping.json');
const copy = readJson('data/exhibit-content.json');
const index = readFileSync('src/exhibits/index.ts', 'utf8');

// Reading these files is deliberate: Phase 13 is not allowed to generate a
// reassuring report after one of its whole-museum guard suites disappears.
readFileSync('tests/accessibility.test.ts', 'utf8');
readFileSync('tests/lifecycle-memory.test.ts', 'utf8');
readFileSync('tests/persistent-environment.test.ts', 'utf8');
readFileSync('tests/environment.test.ts', 'utf8');
readFileSync('tests/traversal.test.ts', 'utf8');

const bespoke = new Set([...index.matchAll(/registerBespoke\(\s*'([^']+)'/g)].map((m) => m[1]));
const mappedIds = new Set(map.exhibits.map((e) => e.id));

const WINGS = {
  north: 'Starsilk & Drakken', east: 'Dex Systems', south: 'Games & Play',
  west: 'Archive & Canon', media: 'Music, Promptcraft & Media', infra: 'Local Systems',
};

const CHECKS = [
  ['reachable', 'tests/traversal.test.ts — walked on the canonical route'],
  ['identifiable', 'signage over every bay opening (Detailing)'],
  ['hero object', 'tests/exhibit-quality.test.ts — real volume in three axes, >12 meshes'],
  ['fits its bay', 'tests/exhibit-quality.test.ts'],
  ['interaction works', 'tests/exhibit-quality.test.ts — controls change observable state'],
  ['reset works', 'tests/exhibit-quality.test.ts — idempotent, returns to just-activated state'],
  ['accessible content', 'tests/exhibit-quality.test.ts — heading, plaque, ≥4 body paragraphs, live state'],
  ['reduced motion', 'tests/exhibit-quality.test.ts — usable and describable with motion off'],
  ['unload / reload', 'tests/exhibit-quality.test.ts — three clean cycles, scope drains to zero'],
  ['owns only its group', 'tests/exhibit-quality.test.ts'],
];

const errors = [];
const lines = [];

lines.push('# Museum of Me vNext — QA Report');
lines.push('');
lines.push('Generated by `npm run qa`. Per-exhibit checks below are enforced by automated tests.');
lines.push('Human visual/device evidence is listed separately and is never promoted automatically.');
lines.push('');
lines.push('## Checklist applied to every exhibit');
lines.push('');
lines.push('| Check | Enforced by |');
lines.push('|---|---|');
for (const [name, by] of CHECKS) lines.push(`| ${name} | ${by} |`);
lines.push('');

const byWing = new Map();
for (const e of map.exhibits) {
  const list = byWing.get(e.wing) ?? [];
  list.push(e);
  byWing.set(e.wing, list);
}

lines.push('## Exhibits');
lines.push('');
let projectTotal = 0;
for (const [wing, name] of Object.entries(WINGS)) {
  const list = byWing.get(wing) ?? [];
  lines.push(`### ${name} — ${list.length} exhibits`);
  lines.push('');
  lines.push('| ID | Exhibit | Tier | Projects | Implementation |');
  lines.push('|---|---|---|---|---|');
  for (const e of list) {
    projectTotal += e.projects.length;
    const impl = bespoke.has(e.id) ? 'bespoke' : '**SCAFFOLDING**';
    if (!bespoke.has(e.id)) errors.push(`${e.id} is still scaffolded`);
    if (!copy[e.id]) errors.push(`${e.id} has no interpretive copy`);
    lines.push(`| ${e.id} | ${e.title} — ${copy[e.id]?.subtitle ?? '—'} | ${e.tier} | ${e.projects.join(', ')} | ${impl} |`);
  }
  lines.push('');
}

for (const id of bespoke) {
  if (!mappedIds.has(id)) errors.push(`bespoke implementation ${id} is not in the frozen mapping`);
}

lines.push('## Whole-museum automated coverage');
lines.push('');
lines.push('- Keyboard, touch, reduced motion, high-contrast/UI-scale preference contract and blur recovery: `tests/accessibility.test.ts`.');
lines.push('- Continuous exterior-to-interior canonical route through every wing and Sanctuary: `tests/traversal.test.ts`.');
lines.push('- Repeated whole-route streaming/lifecycle settling and shell budgets: `tests/lifecycle-memory.test.ts`.');
lines.push('- Always-resident refinement mesh/triangle/material/light/resource budgets: `tests/persistent-environment.test.ts`.');
lines.push('- Garden/daylight, facade, Rotunda baseline, wing identity, furnishings, atmosphere, wayfinding and exhibit colour fields: `tests/environment.test.ts`.');
lines.push('- Mapping, visitor content, privacy, frame-loop, hot-path, assets, bespoke exhibit validation, production build and bundle budgets: canonical `npm run gate`.');
lines.push('');

lines.push('## Coverage');
lines.push('');
lines.push(`- **${map.exhibits.length} / 35** exhibits`);
lines.push(`- **${projectTotal} / 64** project identities represented, each exactly once`);
lines.push(`- **${bespoke.size} / ${map.exhibits.length}** implemented bespoke`);
lines.push('- **1** Dexter Sanctuary, deliberately outside the exhibit count');
lines.push('');
lines.push('## Spaces outside the exhibit count');
lines.push('');
lines.push('| Space | Checks |');
lines.push('|---|---|');
lines.push('| Reliquary Rotunda | reachable, monumental, two-level continuity, orientation and neutral-hub wayfinding |');
lines.push('| Arrival plaza and entrance | reachable, daylight, garden, signed public-building facade |');
lines.push('| Rotunda balcony | reachable by stair, connects both mezzanines |');
lines.push('| Dexter Sanctuary | `tests/sanctuary.test.ts` — below and behind the axis, hanging ears preserved, holds still under reduced motion, contains no score, badge, collectible, paw-print, achievement, unlock or reward |');
lines.push('');
lines.push('## Human-only release evidence still required');
lines.push('');
lines.push('- Recorded visual walkthrough from garden through representative galleries and exhibit bays.');
lines.push('- Pointer-lock capture, look, Escape/loss recovery and recapture on a real browser/device.');
lines.push('- Muted-by-default audio check plus deliberate Sound-control playback/subtitle check.');
lines.push('- Representative-device frame-rate measurement and subjective exposure/clipping/density review.');
lines.push('');
lines.push('See `validation/reports/HUMAN_QA_CHECKLIST.md` for the exact manual route.');

if (projectTotal !== 64) errors.push(`project coverage is ${projectTotal}, expected 64`);
if (map.exhibits.length !== 35) errors.push(`exhibit count is ${map.exhibits.length}, expected 35`);
if (bespoke.size !== map.exhibits.length) errors.push(`bespoke count is ${bespoke.size}, expected ${map.exhibits.length}`);

const manual = [
  '# Museum of Me vNext — Human QA Checklist',
  '',
  'This checklist is intentionally human-only. Completing automated tests does not satisfy it.',
  '',
  '## Recording route',
  '',
  '- [ ] Begin at the real exterior spawn and record the garden-facing museum composition.',
  '- [ ] Walk the central garden path and verify no furnishing clips or blocks the entrance.',
  '- [ ] Enter through the vestibule and verify the bright neutral transition reads cleanly.',
  '- [ ] Circle the Rotunda and balcony; verify the centre stays neutral while all six route threads are legible.',
  '- [ ] Visit North, East, South, West, Media and Infrastructure; inspect threshold identity, atmosphere and wing-specific furnishings.',
  '- [ ] Enter at least one early, middle and late exhibit bay in each wing; confirm colour fields frame rather than overpower bespoke hero objects.',
  '- [ ] Walk to Dexter Sanctuary and back without teleport or route confusion.',
  '- [ ] Return to the exterior entrance.',
  '',
  '## Device interaction',
  '',
  '- [ ] Capture pointer lock with mouse and with keyboard activation of the entry prompt.',
  '- [ ] Verify mouse look, Q/E turn and Page Up/Page Down vertical keyboard look.',
  '- [ ] Press Escape or otherwise lose pointer lock; verify controls recover cleanly and recapture works.',
  '- [ ] Open Map, Journal, Settings and accessible contents using keyboard only; verify focus stays inside panels and returns on close.',
  '- [ ] Toggle reduced motion, high contrast and interface scale; verify each change is immediately visible/operative.',
  '- [ ] Confirm touch fallback on a touch-capable device when available.',
  '',
  '## Audio and performance',
  '',
  '- [ ] Confirm Overall volume and Ambience begin at zero; no sound is audible until a visitor raises them.',
  '- [ ] Raise the Sound controls deliberately and verify opted-in ambience/reactive audio and subtitles behave as expected.',
  '- [ ] Record FPS on a representative device during exterior, Rotunda, a dense wing and a Tier A exhibit.',
  '- [ ] Watch for monotonic memory growth during a long traversal if browser tooling is available.',
  '',
  '## Visual acceptance',
  '',
  '- [ ] Daylight is bright but not washed out.',
  '- [ ] Facade overlays align with the entrance mass and do not look pasted on.',
  '- [ ] Rotunda reads luminous rather than sterile.',
  '- [ ] Wing furnishings add identity without clutter or blocked sightlines.',
  '- [ ] Exhibit colour fields support content rather than competing with it.',
  '- [ ] No visible voids, z-fighting, clipping, broken transparency or obvious texture/geometry failure.',
  '',
];

writeFileSync('validation/reports/QA_REPORT.md', lines.join('\n'));
writeFileSync('validation/reports/HUMAN_QA_CHECKLIST.md', manual.join('\n'));

process.exit(
  report('qa', errors, [
    `${map.exhibits.length} exhibits, ${projectTotal} project identities, ${bespoke.size} bespoke`,
    'wrote validation/reports/QA_REPORT.md',
    'wrote validation/reports/HUMAN_QA_CHECKLIST.md',
  ]),
);
